// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqE_UlVv6hL7LTjlRaC03YQ5eHwKGH9A',
    appId: '1:715062836638:web:79b7a7649adc59dba82a8f',
    messagingSenderId: '715062836638',
    projectId: 'network-social-95eb9',
    authDomain: 'network-social-95eb9.firebaseapp.com',
    databaseURL: 'https://network-social-95eb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'network-social-95eb9.appspot.com',
    measurementId: 'G-V1MFZVJRVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbyS_Q9ODH-A7DoKHhCl0m2EfQmpVwyFA',
    appId: '1:715062836638:android:b6982d7b97cbfe25a82a8f',
    messagingSenderId: '715062836638',
    projectId: 'network-social-95eb9',
    databaseURL: 'https://network-social-95eb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'network-social-95eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCmzC0LVsEnMTqTVM48mE545oo2e-bMM',
    appId: '1:715062836638:ios:7d5013a519a0fcd9a82a8f',
    messagingSenderId: '715062836638',
    projectId: 'network-social-95eb9',
    databaseURL: 'https://network-social-95eb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'network-social-95eb9.appspot.com',
    iosClientId: '715062836638-r6lig340iahk5qqjqhb4pitbb1rrd8ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.sleep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCmzC0LVsEnMTqTVM48mE545oo2e-bMM',
    appId: '1:715062836638:ios:a230657a82b9d61ca82a8f',
    messagingSenderId: '715062836638',
    projectId: 'network-social-95eb9',
    databaseURL: 'https://network-social-95eb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'network-social-95eb9.appspot.com',
    iosClientId: '715062836638-1jirr4vr6lhcl2gbl7v2o2aamgpi63e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwqE_UlVv6hL7LTjlRaC03YQ5eHwKGH9A',
    appId: '1:715062836638:web:d66e1cbd80b40ef9a82a8f',
    messagingSenderId: '715062836638',
    projectId: 'network-social-95eb9',
    authDomain: 'network-social-95eb9.firebaseapp.com',
    databaseURL: 'https://network-social-95eb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'network-social-95eb9.appspot.com',
    measurementId: 'G-KK536KXF0L',
  );
}
